config/routes.rb
TwitterClone::Application.routes.draw do
    resources :users
    resources :tweets
    resources :relationships
    resources :stars
    root to: 'tweets#index'

    get "/username/:username" => 'users#show_name'
    get "login" => 'sessions#new', as: 'login'
    post "login" => 'sessions#create'
    get "signup" => 'users#new', as: 'signup'
    get 'logout' => 'sessions#destroy', as: 'logout'
    get '/users/follow/:id' => 'users#follow'
    get '/users/unfollow/:id' => 'users#unfollow'
    get '/tweets/favorite/:id' => 'tweets#favorite'
    get '/tweets/retweet/:id' => 'tweets#retweet'
    get '/hashtags/:id' => 'hashtags#show'
end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
    has_and_belongs_to_many :tweets

    validates :name, uniqueness: true
    validates :name, presence: true
end

app/models/mention.rb
class Mention < ActiveRecord::Base
    belongs_to :user
    belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
    belongs_to :follower, class_name: "User"
    belongs_to :followed_user, class_name: "User"
end

app/models/retweet.rb
class Retweet < ActiveRecord::Base
    belongs_to :tweet
    belongs_to :user
end

app/models/star.rb
class Star < ActiveRecord::Base
    belongs_to :tweet
    belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    belongs_to :user
    has_many :stars
    has_many :retweets
    
    has_and_belongs_to_many :hashtags

    validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :relationships, class_name: 'Relationship', foreign_key: :followed_user_id
    has_many :followers, through: :relationships

    has_many :reverse_relationships, class_name: 'Relationship', foreign_key: :follower_id
    has_many :followed_users, through: :reverse_relationships

    has_many :tweets
    has_many :stars
    has_many :starred_tweets, through: :stars, source: :tweet

    has_many :mentions
    has_many :mention_tweets, through: :mentions, source: :tweet

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
    def show
        @tag = Hashtag.find(params[:id])
        @tags = Hash.new
        hashtags = Hashtag.all.all? { |tag|  @tags[tag.name] = tag.id}
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:info] = "logged in!"
			redirect_to tweets_path
		else
			flash[:info] = "Invalid email or password"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:info] = "Logged out"
		redirect_to root_url
	end



end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_filter :check_login

    def index
        @tweets = current_user.followed_users.map(&:tweets).flatten + current_user.tweets + current_user.mention_tweets
        @tweets.uniq!
        @tweets.sort_by! {|twt| twt.created_at}
        @tags = Hash.new
        hashtags = Hashtag.all.all? { |tag|  @tags[tag.name] = tag.id}

        @tweet = Tweet.new
        @users = User.all
    end

    def create
    	@tweet = Tweet.new(tweet_params)
    	@tweet.user_id = session[:user_id]
    	if @tweet.save

                        tokens = @tweet.body.strip.split
                        
                        tokens.each do |token|

                            if token[0] == '#' and token.length > 1
                                tag = Hashtag.find_by_name(token)
                                if  tag != nil
                                    @tweet.hashtags << tag
                                else
                                    tag = Hashtag.new
                                    tag.name = token

                                    if tag.save
                                        @tweet.hashtags << tag
                                    end
                                end

                            elsif token[0] == '@' and token.length > 1
                                user = User.find_by_username(token[1..-1])
                                mention = Mention.new
                                mention.user = user
                                mention.tweet = @tweet
                                mention.save
                            end
                        end

    		redirect_to user_path(current_user)
    	else
    		render :new
    	end
    end

    def show
    	@tweet = Tweet.find(params[:id])
    end

    def new
    	@tweet = Tweet.new
    end

    def favorite
        @star = Star.new
        @star.tweet = Tweet.find(params[:id])
        @star.user = current_user

        if @star.save
            redirect_to tweet_path(params[:id])
        else
            redirect_to user_path(current_user)
        end
    end

    def retweet
        @retweeted_tweet = Tweet.new
        @tweet = Tweet.find(params[:id])

        @retweeted_tweet.body = "RT: " + @tweet.body
        @retweeted_tweet.user = current_user

        if @retweeted_tweet.save

                @retweet = Retweet.new
                @retweet.tweet = @tweet
                @retweet.user = current_user

                if @retweet.save
                    redirect_to user_path(current_user)
                else
                    redirect_to root_path
                end

        else
            redirect_to user_path(@tweet.user)
        end
    end

    def hashtag_path(name)
        tag = Hashtag.find_by_name(name)

        @path = "/hashtags/#{tag.id}"
    end
    helper_method :hastag_path

    private
        def tweet_params
        	params.require(:tweet).permit(:body)
        end

        def check_login
        	if session[:user_id] == nil
        		redirect_to login_path
        	end
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


            def index
                @users = User.all
            end
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to "/users/#{@user.id}"
		else
			render :new
		end
	end

	def show

		if session[:user_id] == nil
			redirect_to login_path
		end

		@user = User.find(params[:id])
                        @tweets = @user.tweets + @user.mention_tweets
                        @tweets.sort_by! {|twt| twt.created_at}
		@tweet = Tweet.new
                        @tags = Hash.new
                        @tagged_users = Hash.new
                        hashtags = Hashtag.all.all? { |tag|  @tags[tag.name] = tag.id}
	end

            def show_name
                @user = User.find_by_username(params[:username])
                if @user != nil
                    redirect_to "/users/#{@user.id}"
                else
                    redirect_to root_path
                end
            end


	def follow
		@user = User.find(params[:id])
		if @user 
			@relationship = Relationship.new
			@relationship.follower_id = current_user.id
			@relationship.followed_user_id = @user.id
			if @relationship.save
				redirect_to user_path(current_user)
			else
				redirect_to root_path
			end
		else
			redirect_to root_path
		end	
	end

            def unfollow
                @relationship = Relationship.where(:followed_user_id => params[:id], :follower_id => session[:user_id])
                if @relationship.count > 0
                    Relationship.destroy(@relationship[0].id)
                    redirect_to user_path(current_user)
                else
                    redirect_to root_path
                end
            end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

	def check_login
		if session[:user_id] == nil
			redirect_to login_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/views/hashtags/show.html.erb
<h3><%= @tag.name %></h3>

Tweets: 
<ul>
                    <% @tag.tweets.each do |tweet| %> 
                        <li> 
                                    <% 
                                        tweet.body.strip.split.each do |token|
                                            if token[0] == '#' %>
                                                <%=  link_to "#{token} ", "/hashtags/#{@tags[token]}"%>
                                                <% elsif token[0] == '@'%>
                                                <%=  link_to "#{token} ", "/#{token[1..-1]}" %>
                                            <% else %>
                                                <%= "#{token} " %>
                                            <% end %>
                                        <% end %>
                                (<%= link_to "Fav", "/tweets/favorite/#{tweet.id}" %>) 
                    <% if tweet.user_id != current_user.id %>
                        (<%= link_to "RT", "/tweets/retweet/#{tweet.id}" %>)
                    <% end %>
                         (<%= link_to "View", tweet_path(tweet) %>)

                    </li>
                    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twerker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<nav class='navbar navbar-default'>
		<a class='navbar-brand' href='/'>Twerker</a>
		<ul class='nav navbar-nav'>
			<% if current_user %>
				<li> <%= link_to "My Profile", user_path(current_user) %> </li> 
			<% end %>
			<li><%= link_to "Twerk", new_tweet_path %></li>
			<li><%= link_to "All Users", users_path %> </li>
		</ul>
	</nav>
</div>

<div class='container'>


<% if current_user %>
	<%= "you are logged in as #{current_user.username}" %>
	<%= link_to "Logout", logout_path %>
<% else %>
	<%= link_to "login", login_path %> or
	<%= link_to "Signup", new_user_path %>
<% end %>		



<% if flash[:info] %>
	<div class='alert alert-info'>
		<%= flash[:info] %>
	</div>
<% end %>
<%= yield %>

</div>

</body>
</html>

app/views/tweets/index.html.erb
<div class="page-header">
    <h1> Latest Twerks <small> See what people are saying</small></h1>
</div>


<ul>
                    <% @tweets.each do |tweet| %> 
                        <li> <%= link_to tweet.user.username.capitalize, user_path(tweet.user) %> twerked:
                                    <% 
                                        tweet.body.strip.split.each do |token|
                                            if token[0] == '#' %>
                                                <%=  link_to "#{token} ", "/hashtags/#{@tags[token]}"%>
                                                <% elsif token[0] == '@'%>
                                                <%=  link_to "#{token} ", "/username/#{token[1..-1]}" %>
                                            <% else %>
                                                <%= "#{token} " %>
                                            <% end %>
                                        <% end %>
                                (<%= link_to "Fav", "/tweets/favorite/#{tweet.id}" %>) 
                        (<%= link_to "RT", "/tweets/retweet/#{tweet.id}" %>)
                        (<%= link_to "View", tweet_path(tweet) %>)

                    </li>
                    <% end %>
</ul>

<%= form_for @tweet, url: "/tweets", method: :post do |f| %>
    <%= f.text_area :body %>
    <%= f.submit "Twerk", class: 'btn btn-primary' %>
<% end %>

app/views/tweets/new.html.erb
<div class="page-header">
    <h1> Twerk<small> Start twerking now</small></h1>
</div>

<%= form_for @tweet do |f| %>
	<%= f.text_area :body %>
	<%= f.submit "Twerk", class: 'btn btn-primary' %>
<% end %>

app/views/tweets/show.html.erb
<h1>
<%= @tweet.user.username %> Twerker:
<%= @tweet.body %>
</h1>
<h4>Favorites: <%= @tweet.stars.count %></h4>

<ul>
<% @tweet.stars.each do |star| %>
    <li><%= link_to star.user.username, "/username/#{star.user.username}" %> favorited this</li>
<% end %>
</ul>

<h4>Retwerks: <%= @tweet.retweets.count %></h4>

<ul>
<% @tweet.retweets.each do |retweet| %>
    <li><%= link_to retweet.user.username, "/username/#{retweet.user.username}" %> retweeted this</li>
<% end %>
</ul>

app/views/users/index.html.erb
<div class="page-header">
    <h1> All Tweeters <small> start following </small></h1>
</div>

<ul>
    <% @users.each do |user| %>
        <li><%= link_to  user.username, user_path(user)%>
        <% if user.id != current_user.id %>
            <% if current_user.followed_users.include?(user) %>
                (<%= link_to "unfollow", "/users/unfollow/#{user.id}" %>)
            <% else %>
                (<%= link_to "follow", "/users/follow/#{user.id}" %>)
            <% end %>
        <% end %>
        </li>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1> New User </h1>
<div style="width:400px; text-align:right">
<%= simple_form_for @user do |f| %>
	<strong>Username</strong> <%= f.text_field :username %>
	<br />
	<strong>email</strong>    <%= f.text_field :email %>
	<%= f.input :password %>
	<%= f.input :password_confirmation %>
	<%= f.submit %>
<% end %>
</div>

app/views/users/show.html.erb
 <div class="page-header">
	<h1><%= @user.username.capitalize %> Twerks <small> See all your twerks
			<% if @user.id != session[:user_id] %>
				<% if current_user.followed_users.include?(@user) %>
					<%= link_to "unfollow", "/users/unfollow/#{@user.id}" %>
				<% else %>
					<%= link_to "follow", "/users/follow/#{@user.id}" %> </small>
				<% end %>
			<% end %> </h1>
</div>
	
	
	<% if @user.tweets.count == 0  %>
		No Twerks
	<% else %>


	<h2> Twerks </h2>
		<ul>
		            <% @tweets.each do |tweet| %> 
		                <li> 
		                            <% 
		                                tweet.body.strip.split.each do |token|
		                                    if token[0] == '#' %>
		                                        <%=  link_to "#{token} ", "/hashtags/#{@tags[token]}"%>
		                                    <% elsif token[0] == '@'%>
		                                        <%=  link_to "#{token} ", "/username/#{token[1..-1]}" %>
		                                    <% else %>
		                                        <%= "#{token} " %>
		                                    <% end %>
		                                <% end %>
		                        (<%= link_to "Fav", "/tweets/favorite/#{tweet.id}" %>) 
		            <% if @user.id != current_user.id %>
		            	(<%= link_to "RT", "/tweets/retweet/#{tweet.id}" %>)
		            <% end %>
		            	(<%= link_to "View", tweet_path(tweet) %>)
		            </li>
		            <% end %>
		</ul>

	<% end %>

	<% if @user.followers.count > 0 %>
		<h3> Followers </h3>
		<ul>
			<% @user.followers.each do |follow| %>
				<li> <%= link_to follow.username, user_path(follow) %>
					<% if follow.id != session[:user_id] %>
					<% if current_user.followed_users.include?(follow) %>
						(<%= link_to "Unfollow", "/users/unfollow/#{follow.id}" %>)
					<% else %>
						(<%= link_to "follow", "/users/follow/#{follow.id}" %>) 
					<% end %>
					<% end %>
				</li> 
			<% end %>
		</ul>
	<% end %>

	<% if @user.followed_users.count > 0 %>
		<h3> Following </h3>
		<ul>
			<% @user.followed_users.each do |follow| %>
				<li> <%= link_to follow.username, user_path(follow) %> 
					<% if follow.id != session[:user_id] %>
					<% if current_user.followed_users.include?(follow) %>
						(<%= link_to "Unfollow", "/users/unfollow/#{follow.id}" %>)
					<% else %>
						(<%= link_to "follow", "/users/follow/#{follow.id}" %>) 
					<% end %>
					<% end %>
				</li> 
			<% end %>
		</ul>
	<% end %>

	<% if @user.starred_tweets.count > 0 %>
		<h3>Favorite Twerks</h3>
		<ul>
            <% @user.starred_tweets.each do |tweet| %> 
                <li> 
                    <% tweet.body.strip.split.each do |token| %>
                        <% if token[0] == '#' %>
                            <%=  link_to "#{token} ", "/hashtags/#{@tags[token]}"%>
                        <% elsif token[0] == '@'%>
                            <%=  link_to "#{token} ", "/username/#{token[1..-1]}" %>
                        <% else %>
                            <%= "#{token} " %>
                        <% end %>
                    <% end %>
                        (<%= link_to "Fav", "/tweets/favorite/#{tweet.id}" %>) 

		            <% if @user.id != current_user.id %>
		            	(<%= link_to "RT", "/tweets/retweet/#{tweet.id}" %>)
		            <% end %>
            	</li>
	        <% end %>
		</ul>
	<% end %>


<%= form_for @tweet, url: "/tweets", method: :post do |f| %>
	<%= f.text_area :body %>
	<%= f.submit "Twerk", class: 'btn btn-primary' %>
<% end %>